name: Acceptance Tests

on:
  schedule:
    - cron: "0 13 * * *"
  push: {}
  pull_request:
    types: [opened, synchronize, reopened]

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

env:
  METAL_STACK_CLOUD_API_TOKEN: ${{ secrets.METAL_STACK_CLOUD_API_TOKEN }}

jobs:
  metal:
    name: Acceptance Test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v7
      - uses: hashicorp/setup-terraform@v4

      - name: Init project
        run: terraform init

      - name: Create cluster and get kubeconfig
        run: terraform apply -target local_sensitive_file.kubeconfig --auto-approve
      - name: Deploy service into cluster
        run: terraform apply --auto-approve

      #   # TODO: eventually run some tests here in the future
      #   # this would require to extract the domain and make a call to it

      - name: Destroy service
        run: terraform destroy -target module.metal-app --auto-approve
      - name: Destroy Cluster
        if: always()
        run: terraform destroy --auto-approve -lock=false

      - name: Post failure to Slack
        uses: slackapi/slack-github-action@v4.0.0
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "@here Integration Test: test cluster creation failed!\nAction: ${{ job.status }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}."
            blocks:
              - type: section
                text:
                  type: mrkdwn
                  text: "@here Integration Test: test cluster creation failed!"
              - type: section
                text:
                  type: mrkdwn
                  text: "*Action:* ${{ job.status }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}."
